#!/bin/bash

===================================
### Human genome files download ###
===================================

## 1. Decompress downloaded files in each respective directory ##

# Files: gencode.v45.transcripts.fa.gz, gencode.v45.pc_transcripts.fa.gz, gencode.v45.long_noncoding_RNAs.gtf.gz, gencode.v45.lncRNA_transcripts.fa.gz), according to user's need.
wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/latest_release/GRCh38.primary_assembly.genome.fa.gz
wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/latest_release/gencode.v45.primary_assembly.annotation.gtf.gz

## 2. Decompress downloaded files in each respective directory ##
gunzip GRCh38.primary_assembly.genome.fa.gz &
gunzip gencode.v45.primary_assembly.annotation.gtf.gz
