#!/usr/bin/env Rscript

# In Bash - chmod +x featureCounts_R.R e ./featureCounts_R.R

library(Rsubread)

# Store the BAM files in a vector for use in the code:
bamFiles <- list.files(path = ".../star/2nd", pattern = "SRR.*Aligned.sortedByCoord.out.bam", full.names = T)

# Execute featureCounts
fcResults_out <- featureCounts(
                            bamFiles,
                            annot.ext = "/transcriptome.gtf",
                            isGTFAnnotationFile = T,
                            GTF.featureType = "exon",
                            GTF.attrType = "gene_id",
                            strandSpecific = 2,
                            countReadPairs = T,
                            isPairedEnd = T,
                            requireBothEndsMapped = T,
                            countMultiMappingReads = F,
                            countChimericFragments = F,
                            nthreads = 32
                            )

# Extract the count matrix
fc_countMatrix <- data.frame(fcResults_out[["counts"]])

# Format column names (keep only SRR[0-9]*)
names(fc_countMatrix) <- sapply(strsplit(names(fc_countMatrix), split = "_"), `[[`, 1)

# Export the count matrix
write.csv(fc_countMatrix,"fc_countMatrix.txt",col.names=T, row.names=T,quote=F,sep=",")

save.image()
